// <auto-generated />
using MgPostal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MgPostal.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MgPostal.Models.Envio", b =>
                {
                    b.Property<long>("EnvioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bultos");

                    b.Property<string>("Calle")
                        .IsRequired();

                    b.Property<string>("Destinatario")
                        .IsRequired();

                    b.Property<string>("Direccion_Remitente")
                        .IsRequired();

                    b.Property<string>("Fecha")
                        .IsRequired();

                    b.Property<string>("Forma_Pago")
                        .IsRequired();

                    b.Property<string>("Localidad_Destino")
                        .IsRequired();

                    b.Property<string>("NumeroCalle")
                        .IsRequired();

                    b.Property<string>("Observaciones");

                    b.Property<string>("Piso");

                    b.Property<string>("Remitente")
                        .IsRequired();

                    b.Property<string>("Remito")
                        .IsRequired();

                    b.Property<decimal>("Valor_Declarado");

                    b.HasKey("EnvioId");

                    b.ToTable("Envios");
                });
#pragma warning restore 612, 618
        }
    }
}
